api 연동
Modu-Moija/momo-front pull request #15
Opened 2021-09-09 14:59 UTC by SJLEE316

![image](https://user-images.githubusercontent.com/65484500/132708815-cd2ef24d-e93f-4b20-83ec-8ee885f7d048.png)

1. username 연동 안됨
2. 지금은 한 명이라 바로 출력했지만,  who가 여러 명일 경우에는, 배열로 들어오기 때문에 코드 수정이 필요할 수 있음
3. CSS는 내일 할게유~~!!
4. setting은 post는 잘 되고 있는 상황이고, 아직 result로 넘어가는 것은 아직 안됨 -> 처음 해봐서 찾아가면서 열심히 하는 중,,, 콩콩콩

2021-09-09 15:01 UTC, SJLEE316 reviewed
리액트,,, 재밌는ㄷㅔ 어려워,,,, 코드리뷰 환영합니다 히힛😀

2021-09-09 22:52 UTC, gmldms784 requested changes

2021-09-09 22:52 UTC, gmldms784 commented on src/Pages/Result.tsx
> +	const URL = "https://momoapi.azurewebsites.net"
URL이 API_HOST라는 common variable로 이미 들어가 있어요!
그거 사용해야 나중에 변경되어도 한번에 고치기 좋을 것 같아요 :)

2021-09-09 22:52 UTC, gmldms784 commented on src/Pages/Result.tsx
> +			.catch((err) => {
지금 작성해둔 코드들 보면 catch 문을 따로 이렇게 작성 안하고 있는데,
error handling이 api 코드 상에 추가되면 너무 길어져서 그래요!
변수로 받고 error handling은 상위에서 한번만 공통으로 처리하는 게 좋을 것 같습니다 :)

2021-09-13 12:17 UTC, SJLEE316 commented
휴 api 연동 신기하다 끌끌끌😜

2021-09-21 12:56 UTC, merged