링크 복사 모달창_로직만 구현
Modu-Moija/momo-front pull request #18
Opened 2021-11-16 14:42 UTC by SJLEE316

아직 머지하지 말아주세요 :)
resolve #17 

### 1. 링크 생성하기 누르면
![image](https://user-images.githubusercontent.com/65484500/142005252-dd5bed69-4b97-4a85-bc80-599e284d16d7.png)

### 2. 링크 복사하기 누르면
![image](https://user-images.githubusercontent.com/65484500/142005311-f6982b2e-54a7-44bd-8b93-aa40984fb4a1.png)

### 3. X or 확인 누르면 로그인 창으로 이동
![image](https://user-images.githubusercontent.com/65484500/142005390-5e280734-95a4-4293-b747-73622e1988f1.png)

### 앞으로 해야할 일
- [ ] [일정이름]이 생성되었습니다! -> 일정이름 연동받아오기
- [ ] 디자인하기
- [ ] 링크복사하기 -> 기능 구현하기

2021-11-16 16:29 UTC, SJLEE316 commented on src/Pages/Setting.tsx
> +					<ModalBox
모달창 형태가 비슷해서 컴포넌트로 분리해봤는데
코드가 더 길어져서 뭐가 정답인지 모르겠다😂

2021-12-05 01:51 UTC, bucketressi approved these changes

2021-12-05 01:51 UTC, bucketressi commented on src/Components/ModalBox.tsx
> +					{text.split("\n").map((txt) => (
이건 따로 utils 폴더를 만들어서 함수를 만드는 것도 좋아보여요!
input으로 Text string을 받고 '\n' 마다 <p></p> tag 단위로 끊어서 만들어서 return 해주는 함수요..!

2021-12-05 01:51 UTC, bucketressi commented on src/Components/ModalBox.tsx
> +					{text.split("\n").map((txt) => (
스타일 통일 되어있다면 전 이렇게 컴포넌트로 만드는거 좋아보입니다 :)

2021-12-05 01:52 UTC, bucketressi commented
수고하셨어요 소정님 :) 복사 로직만 완성하면 되네용

2021-12-19 06:42 UTC, SJLEE316 commented
오랜만에 pr들고왔는데 구현한건 아무것도 없네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ퓨ㅠㅠ퓨

2021-12-23 13:03 UTC, bucketressi requested changes

2021-12-23 13:03 UTC, bucketressi commented on src/utils/NewLine.ts
> +export function NewLine(text: String): String {
```js

export const convertNewLineToP = (newLineString : string) => {
  if (!newLineString) {
    return [];
  }
  const splitedWordList = newLineString.split('\n');
  const elementList = splitedWordList.map((word, index) => {
    const key = `${word}-${index}`;
    if (word === '') {
      return <br key={key} />;
    }
    return (
      <p key={key}>{ word }</p>
    );
  });
  return elementList;
};
```

이거 이용해보실래용?

```

2021-12-30 06:29 UTC, SJLEE316 commented on src/utils/NewLine.ts
> +export function NewLine(text: String): String {
@bucketressi 
`return <br />`하고 `return <p></p>`에서 계속 에러가 발생하더라구용,,, 함수로 작성하고 싶었는데 그냥 컴포넌트로 처리했어요 쀼앵,,,

2022-01-03 06:23 UTC, SJLEE316 commented
## 현재상황
컴포넌트로 처리해서
- 링크 복사하기 버튼
- 확인 버튼
이렇게 버튼이 사용되고 있어요!

## 문제상황
링크 복사하는 라이브러리 react-copy-to-clipboard를 사용하려고 했는데, 모달창 컴포넌트에 그대로 사용하면 확인 버튼에도 링크복사하기 기능이 적용되는데... 흐음.... 어떻게 하는게 좋을까요?

## 해결방안
함수를 직접 구현하는 방법도 생각해보았는데
https://tttap.tistory.com/126
주소를 어디에 담아서 그걸 select해서 copy를 하더라고요..! (비효율적)

2022-01-04 06:40 UTC, bucketressi commented on src/utils/NewLine.ts
> +export function NewLine(text: String): String {
엥 왜일까요..? ts로 해서 그런가 확장자를 .tsx로 해보시겠어요?

2022-01-04 06:42 UTC, bucketressi commented
소정님! 링크 복사하기는 말씀하신 tistory 형식으로 하는게 좋아요! 나중에 앱이나 다른 플랫폼에서도 처리가 통일되어야 해서 저렇게 native code로 짜는 것이 좋답니다. 다만 라이브러리 사용하고 계시니 그대로 해도 상관없을 것 같아용!

2022-02-12 03:11 UTC, SJLEE316 commented
```
const myURL = window.location.href + `result/${url}`;
```
로 해서 링크 설정했어요..!!

2022-02-12 03:12 UTC, SJLEE316 commented on src/utils/NewLine.ts
> +export function NewLine(text: String): String {
이 부분은 곧 다시 해보겠습니당

2022-02-20 08:36 UTC, bucketressi approved these changes
감사합니다!

2022-02-21 12:27 UTC, merged